### PR TITLE
Added how-to-contribute page

### PR DESCRIPTION
**Pull request by minimalparts**
I've added a minimal 'how to contribute' page, as a couple of people have been requesting it.

### CODE REVIEW

**Comment by sepulchered** [comment]
Could you also provide links to relevant linguistics/statistics resources to better understand logic behind the code?

**Comment by minimalparts** [comment]
Sure. I was anyway planning on adding a page linking to the papers we have published about the system. I'll create that and link to it from the contributors' page.

**Comment by minimalparts** [comment]
Ok. I've added an extra background page. @PeARSearch/all-pears, unless anybody complains, I'll merge tonight.

**Comment by nandajavarma** [comment]
These is a slight CSS break in the page. With the active class. I will fix this soon

**Pull request merged**
